apps/events/admin.py

register models

---

apps/events/templates/events/list.html

Added Uncategorized option if no event.category is chosen

added Uncategorized for event.category

---

apps/events/fixtures/category_fixture.json
apps/events/migrations/0013_create_event_categories.py
entrypoint-mac.sh
entrypoint.sh

added fixtures for categories

---

README.md
gcpCredentials.json

How to run (temporary, to be new main branch) rest-api branch locally.
The same applies to any other branches

How to run (temporary, to be new main branch) rest-api branch locally

---

.pre-commit-config.yaml
apps/core/helpers.py
apps/core/serializers.py

Added jwt claims
Removed username login
Updated linter versions

Removed username login, added extra claims to jwt

---

apps/core/tests/tests_logout.py

test_valid, test_token_invalid, test_token_blacklisted

Logout tests

---

apps/core/serializers.py
apps/core/urls.py
apps/core/views.py

- Added /email-exists URL in `urls.py` routing to `EmailExistsView`.
- Implemented `EmailExistsView` in `views.py` to check user email existence.
-  Implemented `EmailCheckSerializer`  in `serializers.py`
Aims to facilitate email existence checks within the core app.

Added POST /email-exists endpoint

---

templates/emails/email_verification.html
templates/emails/reset_password.html

Change mail templates

---

apps/core/tests/models.py
apps/core/tests/tests_reverify_email.py
apps/core/views.py

test_valid, test_email_blank, test_email_invalid, test_email_verified. Corrected ReverifyEmailView with getting user.

email reverify tests

---

apps/profiles/consumers.py
apps/profiles/managers.py
apps/profiles/tests/websockets/tests_accept_notifications.py
apps/profiles/tests/websockets/tests_follow_notifications.py
apps/profiles/tests/websockets/tests_follow_request_notifications.py
apps/profiles/viewsets.py

```python
{
'created': '2024-04-09T08:42:28.365154', 
'data': {
'to_user_id': 4, 
'to_username': 'penguin'
'from_user_id': 3, 
'from_user_image_url': None, 
'from_username': 'cowboy', 
'follower_status': 'ACCEPTED', 
}, 
'type': 'follow'}
```

New notifications payload looks like this

---

apps/events/permissions/events.py
apps/events/viewsets.py

Added action method and increase event permission

Add kick functionality for creators

---

apps/core/urls.py
apps/core/views.py

Added endpoint and viewset class

Change email functionality

---

.pre-commit-config.yaml
apps/profiles/filters/filters_followers.py
apps/profiles/viewsets/followers.py

Created filtering users with two custom FilterSet class for each methods: list_followers() and list_following().

Filtering follows followers

---

apps/conftest.py
apps/events/permissions/events.py
apps/events/serializers/events.py
apps/events/tests/conftest.py
apps/events/tests/events/constants.py
apps/events/tests/events/tests_events_create.py
apps/events/tests/events/tests_events_created.py
apps/events/tests/events/tests_events_delete.py
apps/events/tests/events/tests_events_get.py
apps/events/tests/events/tests_events_get_private.py
apps/events/tests/events/tests_events_list.py
apps/events/tests/events/tests_events_partial_update.py
apps/events/tests/events/tests_events_participated.py
apps/events/tests/events/tests_events_update.py
apps/events/viewsets/events.py

- Fixed get_private url path;
- Some fixes in serializers;
- Fixed create permission.

Events base tests

---

apps/chats/consumers.py
apps/chats/exceptions.py
apps/chats/serializers/chats.py
apps/core/middlewares.py
apps/core/utils.py
apps/core/views/emails.py
apps/core/views/passwords.py
apps/events/viewsets/events.py
apps/notifications/base.py
apps/notifications/consumers.py
apps/profiles/exceptions.py
apps/profiles/utils.py
apps/profiles/viewsets/profiles.py
apps/upload/utils.py
config/settings.py

I tried to use the logs types in the right way

Little logging fix

---

apps/conftest.py
apps/events/tests/conftest.py
apps/profiles/tests/prifiles/tests_profile_get.py
apps/profiles/tests/prifiles/tests_profile_update.py

Tested patch method to add user location data

Added: tests partial update user location

---

apps/conftest.py
apps/events/tests/conftest.py
apps/events/tests/events/tests_events_serializer_utils.py
apps/profiles/tests/prifiles/tests_profile_update.py

1. Rename variable city_location_default_data to city_location_data
2. Added test if existing users location changed

Added: tests update user with exist location

---

apps/conftest.py
apps/events/serializers/utils.py
apps/profiles/tests/prifiles/tests_profile_update.py

1. Fixed  method update_city_if_exist for saving changing place_id to City
2. Fixed changing city_location in instance, if city exists in base
3.  Added additional assertions to test

Dev profile update location

---

apps/events/serializers/__init__.py
apps/events/serializers/city.py
apps/events/urls.py
apps/events/viewsets/__init__.py
apps/events/viewsets/city.py

Added endpoint getting place_id list

Dev get city place_id list

---

apps/conftest.py
apps/profiles/serializers/__init__.py
apps/profiles/serializers/following.py
apps/profiles/tests/followers/tests_list_followers.py
apps/profiles/tests/followers/tests_list_following.py
apps/profiles/viewsets/followers.py

Added serialize for Followings, check point by "username" in tests.

Fixed return followings username

---

apps/chats/serializers/messages.py
apps/chats/viewsets/chats.py
apps/chats/viewsets/messages.py
apps/conftest.py
apps/profiles/tests/followers/constants.py
apps/profiles/tests/followers/tests_kick_follower.py
apps/profiles/viewsets/followers.py

Added functionality to kick followers

add_kick_follower
